"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-19 02:40:33.914911
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_at'), 'audit_logs', ['at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('chains',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('live_trading_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_at'), 'events', ['at'], unique=False)
    op.create_index(op.f('ix_events_correlation_id'), 'events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('token_key', sa.String(length=200), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_at'), 'market_snapshots', ['at'], unique=False)
    op.create_index(op.f('ix_market_snapshots_token_key'), 'market_snapshots', ['token_key'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('token_key', sa.String(length=200), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('final_action', sa.String(length=8), nullable=False),
    sa.Column('final_reason', sa.Text(), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('ai_status', sa.String(length=16), nullable=False),
    sa.Column('sized_amount_usdc', sa.Float(), nullable=False),
    sa.Column('strategy_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk_limits', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('controls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('wallet_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('market', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_created_at'), 'decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_decisions_token_key'), 'decisions', ['token_key'], unique=False)
    op.create_index(op.f('ix_decisions_user_id'), 'decisions', ['user_id'], unique=False)
    op.create_index('ix_decisions_user_token_created', 'decisions', ['user_id', 'token_key', 'created_at'], unique=False)
    op.create_table('launchpads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('descriptor', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'name')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('token_address', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('requested_amount_usdc', sa.Float(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('fee_usdc', sa.Float(), nullable=False),
    sa.Column('slippage_pct', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_decision_id'), 'orders', ['decision_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index('uq_orders_idem_active', 'orders', ['idempotency_key'], unique=True, postgresql_where=sa.text("status NOT IN ('FAILED','REJECTED')"))
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('cash_usdc', sa.Float(), nullable=False),
    sa.Column('starting_cash_usdc', sa.Float(), nullable=False),
    sa.Column('realized_total_usdc', sa.Float(), nullable=False),
    sa.Column('realized_today_usdc', sa.Float(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mode')
    )
    op.create_table('positions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('launchpad', sa.String(length=64), nullable=True),
    sa.Column('token_address', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('initial_quantity', sa.Float(), nullable=False),
    sa.Column('cost_basis_usdc', sa.Float(), nullable=False),
    sa.Column('total_invested_usdc', sa.Float(), nullable=False),
    sa.Column('realized_pnl_usdc', sa.Float(), nullable=False),
    sa.Column('peak_price', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('tiers_hit', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_new_high_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('signing_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('tx', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signing_requests_user_id'), 'signing_requests', ['user_id'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'user_id', 'version')
    )
    op.create_table('tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('creator_address', sa.String(length=128), nullable=True),
    sa.Column('launchpad', sa.String(length=64), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'address')
    )
    op.create_table('wallets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('ownership_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chain', 'address')
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_decision_id'), 'ai_analyses', ['decision_id'], unique=False)
    op.create_table('pools',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('token_id', sa.String(length=32), nullable=False),
    sa.Column('launchpad', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'address')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('portfolio_id', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash_usdc', sa.Float(), nullable=False),
    sa.Column('exposure_usdc', sa.Float(), nullable=False),
    sa.Column('total_value_usdc', sa.Float(), nullable=False),
    sa.Column('daily_pnl_usdc', sa.Float(), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_at'), 'portfolio_snapshots', ['at'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_portfolio_id'), 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=8), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_decision_id'), 'risk_assessments', ['decision_id'], unique=False)
    op.create_table('strategy_signals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_signals_decision_id'), 'strategy_signals', ['decision_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('position_id', sa.String(length=32), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('notional_usdc', sa.Float(), nullable=False),
    sa.Column('fee_usdc', sa.Float(), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_at'), 'trades', ['at'], unique=False)
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=False)
    op.create_index(op.f('ix_trades_position_id'), 'trades', ['position_id'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_table('wallet_policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('wallet_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_policies_wallet_id'), 'wallet_policies', ['wallet_id'], unique=False)
    op.create_table('wallet_authorizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('wallet_id', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=32), nullable=False),
    sa.Column('policy_id', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_ref', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['wallet_policies.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_authorizations_wallet_id'), 'wallet_authorizations', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_authorizations_wallet_id'), table_name='wallet_authorizations')
    op.drop_table('wallet_authorizations')
    op.drop_index(op.f('ix_wallet_policies_wallet_id'), table_name='wallet_policies')
    op.drop_table('wallet_policies')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_position_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_at'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_strategy_signals_decision_id'), table_name='strategy_signals')
    op.drop_table('strategy_signals')
    op.drop_index(op.f('ix_risk_assessments_decision_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_portfolio_snapshots_portfolio_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_at'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_table('pools')
    op.drop_index(op.f('ix_ai_analyses_decision_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_table('tokens')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_signing_requests_user_id'), table_name='signing_requests')
    op.drop_table('signing_requests')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('portfolios')
    op.drop_index('uq_orders_idem_active', table_name='orders', postgresql_where=sa.text("status NOT IN ('FAILED','REJECTED')"))
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_decision_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('launchpads')
    op.drop_index('ix_decisions_user_token_created', table_name='decisions')
    op.drop_index(op.f('ix_decisions_user_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_token_key'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_created_at'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_market_snapshots_token_key'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_at'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_correlation_id'), table_name='events')
    op.drop_index(op.f('ix_events_at'), table_name='events')
    op.drop_table('events')
    op.drop_table('chains')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
